### ISSUE TITLE
Can't compile on OSX 10.11

### ISSUE THREAD

**Issue by keinkurt** [martinrotter/rssguard#43]
#### Brief description of the issue.

Make of RSS Guard failed with errors on Mac OSX 10.11.6

#### How to reproduce the bug?

* Install qt 5.7.0 from homebrew with
```bash
brew install https://raw.githubusercontent.com/LRFLEW/homebrew-core/981fa2e8f824b068077e7df47f81bdb8d93a8ea1/Formula/qt5.rb
```
* Create build folder
* Clone RSS Guard to folder ../rssguard
* Run
```bash
sudo qmake ../rssguard/rssguard.pro -r CONFIG+=release PREFIX=/usr/local INSTALL_ROOT=./app
```
* Run
```bash
sudo make
```

#### What is the expected result?

Successfully compiling

#### What actually happened?

```bash
../rssguard/src/gui/dialogs/formabout.cpp:38:38: error: use of undeclared identifier 'APP_ICON_PATH'
  m_ui->m_lblIcon->setPixmap(QPixmap(APP_ICON_PATH));
                                     ^
../rssguard/src/gui/dialogs/formabout.cpp:73:20: error: use of undeclared identifier 'APP_INFO_PATH'
  file.setFileName(APP_INFO_PATH + QL1S("/COPYING_GNU_GPL_HTML"));
                   ^
../rssguard/src/gui/dialogs/formabout.cpp:82:20: error: use of undeclared identifier 'APP_INFO_PATH'
  file.setFileName(APP_INFO_PATH + QL1S("/COPYING_BSD"));
                   ^
../rssguard/src/gui/dialogs/formabout.cpp:91:20: error: use of undeclared identifier 'APP_INFO_PATH'
  file.setFileName(APP_INFO_PATH + QL1S("/CHANGELOG"));
                   ^
```

#### Other information (logs, see Wiki)

```bash
uname -a
Darwin DRSM33795167A 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```
```bash
clang++ --version
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
```bash
qmake --version
QMake version 3.0
Using Qt version 5.7.0 in /usr/local/Cellar/qt5/5.7.0/lib
```

**Comment by martinrotter** [comment]
Yes, the support for Mac OS X is problematic since I do not own Mac machine by myself. I will try to make  some blind fixes.

**Comment by martinrotter** [comment]
Basically we need to do only two things:

1. Tweak file `src/definitions/definitions.h` and add OS X defines into it.
2. Tweak project file `rssguard.pro` and specify where files should be "installed" in `make` step.

**Comment by martinrotter** [comment]
Okay, PR merged. I made couple of blind tweaks which I think will make it fully functional internally in RSS Guard (loading skins, DB code etc).

Please test https://github.com/martinrotter/rssguard/commit/299833f72ba341ccca718a2285d2b909c3d710dc.

**Comment by martinrotter** [comment]
Can we close this?

**Comment by keinkurt** [comment]
Yes, it works for me with some limitations, like no app icon and no .dmg installation file. But the app compiles and I can start and use it.

**Comment by martinrotter** [comment]
Wow, that's perfect, can you post some screenshots? + Can you compile dmg file?

**Comment by martinrotter** [comment]
Hello, I plan to add auto-building of RSS Guard for OSX on Travis CI.

Can you post full set of working command for building rssguard?

**Comment by keinkurt** [comment]
Actually the building process doesn't work on my machine and I have no time to investigate it.

**Comment by martinrotter** [comment]
I managed to setup automatic DMG/bundle compilation via Travis CI.

Sample DMG is [here](https://transfer.sh/9i4ct/rssguard.dmg). [Here ](https://travis-ci.org/martinrotter/rssguard)you can see build status. DMG files are automatically updated after each build. Always checkout [build log](https://travis-ci.org/martinrotter/rssguard/jobs/154717323) at the bottom, where the link is located.
